# Конфигурация Mephist Data KIT

# Настройки подключения
server:
  base_url: "https://tokamak.mephi.ru/"
  base_path: "/orders/shots-api/"
  verify_ssl: true                  # для самоподписанных сертификатов

# Аутентификация ПОМЕНЯЙТЕ ТОКЕН НА СВОЙ
auth:
  api_token: "EigVwAYnuNqmt47mrD6bLsgezGQR84hbLTD6RSoTHU2FTVfSld3YWRSTaBlp"

# Настройки загрузки данных
download:
  chunk_size: 8192                  # Размер чанка для скачивания
  timeout: 5                        # Таймаут запроса (секунды)
  retry_attempts: 3                 # Количество попыток при ошибке
  show_progress: true               # Включить/выключить прогресс-бар

# Настройки кэширования данных
cache:
  use_cache: true                   # Использовать кэш по умолчанию (в противном случае каждый раз будет скачиваться с сервера)
  cache_dir: "./.cache"              # директория для хранения кэша (Создаётся автоматически)
  cache_max: "3 GB"                 # Макксимальный размер кэша в формате "500 MB", "1GB", "100KB" и "0" для отключения ограничения

logging:
  console_level: "INFO"             # Уровень вывода сообщений в консоль: ERROR, WARNING, INFO