auth:
  api_token: C8yvwmWZ8THNjwBgaBJz43DWomyl3yNcStgwTXf3hAd3WaXNqtlI46kRaD5L
cache:
  cache_dir: ./.cache
  cache_max: 3 GB
  use_cache: true
download:
  chunk_size: 8192
  retry_attempts: 3
  show_progress: true
  timeout: 5
logging:
  console_level: INFO
server:
  base_path: /orders/shots-api/
  base_url: https://tokamak.mephi.ru/
  verify_ssl: true
